### ISSUE TITLE
How to test on arbitrary images?

### ISSUE THREAD

**Issue by rakhecha42** [leimao/DeepLab_v3#6]
Hello. Newbie enthusiast here.  I was just wondering if you could give a rough idea on how to test a pretrained model with random images so I can write the script on my own. Thanks!

**Comment by leimao** [comment]
Hi @rakhecha42 ,
This is a very reasonable request, I think I will work on it during my casual time. However, if you are familiar with Python and you really need some clues for now, check the `test_demo.py` file, which contains almost everything you wanted except the image resizing for arbitrary images.
Best,
Lei

**Comment by leimao** [comment]
Thanks to @pinaxe1 , we have a script to test custom images now. Sorry I have been busy and have not been finding time to manage the repo.
